name: data
on:
  schedule:
    - cron: 10 6 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess-iryo.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.kantei.go.jp/jp/content/IRYO-vaccination_data.xlsx
          downloaded_filename: IRYO-vaccination_data.xlsx
          postprocess: ./postprocess-iryo.ts
