name: publish
on:
  schedule:
    - cron: 10 6 * * *
  workflow_dispatch: {}
  push:
    paths-ignore:
      - 'data'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.5
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "~/.poetry/bin" >> $GITHUB_PATH
      - name: Enable project local virtualenv
        run: poetry config virtualenvs.in-project true
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: poetry install --no-interaction
      - name: Convert visualize script to Jupyter Notebook
        run: ./.venv/bin/ipynb-py-convert visualize.py visualize.ipynb
      - name: Update data
        run: ./.venv/bin/python3 ./app.py
      - name: Generate visualization html
        run: ./.venv/bin/jupyter nbconvert --output-dir='docs' --output='index.html' --to='html' --execute visualize.ipynb
      - name: Commit files
        run: |
          git config --local user.email "bankruptko@protonmail.com"
          git config --local user.name "bankruptko"
          git add ./data
          git add ./docs
          git add ./visualize.ipynb
          git commit -am "Update data and visualization"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}