name: publish
on:
  schedule:
    - cron: 10 6 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/publish.yml
      - ./app.py
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.5
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "~/.poetry/bin" >> $GITHUB_PATH
      - name: Enable project local virtualenv
        run: poetry config virtualenvs.in-project true
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: poetry install --no-interaction
      - name: Publish
        run: ./.venv/bin/python3 ./app.py
      - name: Commit files
        run: |
          git config --local user.email "bankruptko@protonmail.com"
          git config --local user.name "bankruptko"
          git add ./data
          git commit -am "Update data files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output